# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [2]:
np.array([0.]*10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [3]:
np.array([1.]*10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [4]:
np.array([5.]*10)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [6]:
np.array(range(10,51))

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [7]:
np.array(range(10,51,2))

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
np.matrix(range(0,9)).reshape(3,3)

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

#### Create a 3x3 identity matrix

In [9]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [32]:
np.random.rand(1)

array([0.25803415])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [33]:
np.random.randn(4,5)

array([[-0.57201084, -0.18669731,  0.39583758, -0.14795143,  0.12784531],
       [ 0.13139151,  0.21974057, -0.19897626,  0.31647518,  0.12176553],
       [ 1.57688617,  0.21073667,  0.17596311,  1.13492876, -0.99755597],
       [-0.88855645,  1.04088258,  1.20601812,  0.66065271,  0.39859521]])

#### Create the following matrix:

In [34]:
np.random.rand(10,10)

array([[0.03630144, 0.44940142, 0.95414714, 0.20950386, 0.01539973,
        0.17664414, 0.16061976, 0.34411556, 0.98427309, 0.9486276 ],
       [0.57306338, 0.35465607, 0.30415774, 0.02445203, 0.08142397,
        0.04393673, 0.59185339, 0.80857325, 0.31919503, 0.51744821],
       [0.2487507 , 0.70954301, 0.48712855, 0.85314938, 0.83631577,
        0.77841286, 0.50723407, 0.80071188, 0.40492292, 0.20777908],
       [0.66066295, 0.77525735, 0.58942731, 0.32873375, 0.15794238,
        0.80554042, 0.18145554, 0.06498014, 0.390783  , 0.98782916],
       [0.79920308, 0.53993473, 0.71690824, 0.32176632, 0.7112309 ,
        0.22625577, 0.5497477 , 0.51232866, 0.56125714, 0.45918023],
       [0.27872359, 0.06155001, 0.65177408, 0.75424271, 0.80069648,
        0.19035675, 0.72796294, 0.25247437, 0.13593819, 0.61042219],
       [0.59975337, 0.27433749, 0.21246438, 0.48080294, 0.6052761 ,
        0.48807044, 0.51481429, 0.56821219, 0.17691657, 0.73638811],
       [0.86091408, 0.32527071, 0.2393454

#### Create an array of 20 linearly spaced points between 0 and 1:

In [35]:
np.linspace(0,1,num=20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [86]:
a=np.array(np.matrix(range(1,26)).reshape(5,5))
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [85]:
b=a[2:5,:]
c=b[:,1:5]
np.array(c)

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [91]:
a[3,4]

20

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [95]:
b=a[:,1:2]
c=b[0:3,:]
c

array([[ 2],
       [ 7],
       [12]])

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [98]:
a[4:5,:]

array([[21, 22, 23, 24, 25]])

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [99]:
a[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [102]:
a.sum()

325

#### Get the standard deviation of the values in mat

In [105]:
np.std(a)

7.211102550927978

#### Get the sum of all the columns in mat

In [103]:
sum(a)

array([55, 60, 65, 70, 75])

# Great Job!